### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Maniues** [typesupply/opentype-cookbook#38]
Hi!
I read #16 issue and I would like to say something important to @typesupply .
Firstly, I made this issue, because #16 is old and closed issue.
 #16 issue was the very chaotic discussion about free and non-free licenses.
The people that were writing the messages in that discussion wanted to say "I'm right, not you!".
Summary:
@typesupply used CC-BY-NC-SA to his work (opentype cookbook)
Person named "Ido" wanted to have this project under free license.
@typesupply disagrees and talks about the unpleasant experiences with free software lawyers while praising corporate lawyers.
---
My opinion about that discussion:
- Yes, I'm fan of the free licensing, **but** I don't want to talk about lots of positives and ask @typesupply to change the license.
- Free Software/Culture lawyers are normal lawyers, not pseudo-lawyers. Much depends on the person. Remember that when you talk to corporate lawyers you pay them a lot, while free software lawyers are sometimes even free.
Also, remember that corporate lawyers will help you copyright your work and limit whatever they can, while free software lawyers look for a way to say, "It's free."
- The magic of free software is that people do something for free. @typesupply,  it's not waste of time. It's type of charity.
---
# Important
Information to @typesupply: I am not negating your decision to license CC-BY-NC-SA, but you must know that now you are not full copyright owner, and you cannot use this cookbook for commercial purposes (you must comply with CC-BY-NC-SA too), because you got some contributions from contributors that used CC-BY-NC-SA, so that contributions are CC-BY-NC-SA too. Now you are licensee of CC-BY-NC-SA.
If you want to change this, you can ask [contributors](https://github.com/typesupply/opentype-cookbook/graphs/contributors). If all contributors agree, you can change license to CC-BY-SA (or another), or just get a permission to use contributions under other terms. You can ask them for permission to relicense their contributions under CC-BY. Then you can use their contributions under CC-BY (all another people also can), but you still can license cookbook under CC-BY-NC-SA.

**Comment by typesupply** [comment]
I'm sorry, but I don't have time for these philosophical discussions.

**Comment by Maniues** [comment]
@typesupply It's not philosophical discussions. I'm sorry if you understood it that way.
I don't want to make a discussion. The most important part is part "Important".
In my post I wrote "I am not negating your decision to license CC-BY-NC-SA". Is it philosophical discussion? It's your choise to make it under CC-BY-NC-SA. Yes, there is my opinion about, but I understand you. You spent your time on writing this cookbook, so it's your decision. 
# In my post I wrote potential dangers of CC-BY-NC-SA FOR YOU! Not for me. For me it may be CC-BY-NC-SA. 
## But **it's NOT** danger like
 _it must be free. Make it free. non-commercial is a danger for you. Big Corps will destroy you_
Please, read my post. I understand you. You wasted your time a lot on discussing in #16.
