### ISSUE TITLE
License for code, images and HTML/CSS elements

### ISSUE THREAD

**Issue by Maniues** [typesupply/opentype-cookbook#39]
Hi!
@typesupply When the cookbook is under CC-BY-NC-SA and fonts are copyrighted, code samples are public domain, what is the license of HTML elements , CSS and images (svgs and ico etc) in docs/?
I recommend:
- CC-BY-NC-SA for images (but some are simple, so some images are in the public domain)
- for CSS,SCSS: public domain OR CC-BY 4.0
- HTML and all js, ruby samples: public domain 
Public domain should be replaced with CC0

@typesupply I prepared COPYRIGHT file of it, so please tell me what you think about licensing above. Then, I can push pull request with all notices.

**Comment by typesupply** [comment]
Please leave me alone. I don't have time for this.

**Comment by Maniues** [comment]
ok
