### ISSUE TITLE
Page blocked by `fonts.css`

### ISSUE THREAD

**Issue by colinmford** [typesupply/opentype-cookbook#48]
Hey @typesupply,

It's coming up on the time of year I have my font production class and thus am referencing this site quite a lot (because it's so useful!). However for me at least the site loads really really slow so it's hard to reference during class.

Using the inspector, I see that there is a call to `http://static.typesupply.com/opentype-cookbook/fonts.css` that times out, and the page is held up while waiting for that CSS file. 

https://github.com/typesupply/opentype-cookbook/blob/a381c400e8bdf6eee3ccc44fc19aafe98bdb9931/docs/media/main.scss#L62

<img width="1187" alt="image" src="https://github.com/typesupply/opentype-cookbook/assets/671409/0fdfdf09-d7d8-4c10-ad2d-73fa5fd86b4c">

I'm not sure what's going on with that server — if the files were simply missing it would get a 404 and move on, so the timeout is kinda strange — but that seems to be the cause.

**Comment by typesupply** [comment]
Ohhh! Thanks for looking into this. The static site went away when WebFaction shut down and I haven't ever figured out (or had the time to deal with) getting the fonts linked up again. So, it was calling a shut down server. Hopefully this fixes it.

**Comment by colinmford** [comment]
🔥🚀 Blazing fast now! Webperf!
